### ISSUE TITLE
How can we ensure that we use the same MMD version in rebuilder and dmci?

### ISSUE THREAD

**Issue by mortenwh** [metno/catalog-rebuilder#10]
https://github.com/metno/catalog-rebuilder/blob/cc6cd0d34af1a000bd4584225f7d71c430186b82/Dockerfile#L7

**Comment by magnarem** [comment]
This is a CI/CD issue. How to solve this I am not sure. I am sure this is not a special case when it comes to CI/CD, so maybe some people at IT with experience with git-lab CI/CD can point us in the right direction.

One solution that comes to mind, is to create a base docker image/container with the mmd installed, and then both the dmci-container and the catalog-rebuilder container will do their own custom building using that container image as base.
This will mean another repo for building just that container.

**Comment by magnarem** [comment]
For now this is added to the documentation : https://gitlab.met.no/tjenester/s-enda/-/blob/workflow_for_MMD_updates/workflows.md?ref_type=heads
