### ISSUE TITLE
Add monitoring of catalog-rebuilder website

### ISSUE THREAD

**Issue by mortenwh** [metno/catalog-rebuilder#11]
We should add monitoring of https://catalog-rebuilder.s-enda*.k8s.met.no/status /admin /dmci

**Comment by magnarem** [comment]
There are multiple ways to do this.

The simplest one, is to set up Prometheus to use HTTP probe to check if `/status` and `/dmci` endpoints respond with HTTP code 200OK. This will be on the Prometheus side, hence no need to add changes to catalog-rebuilder.

Another solution is to implement a `/health` -endpoint in catalog-rebuilder, which gives a Prometheus compatible page with the catalog integrity status as well as # of files in rejected and workdir folders.
Then it would be possible to add alerts for certain conditions. This is probably the best solution for the future, but involves a little bit of implentation in catalog-rebuilder. Not to much since most of the logic are there already.

**Comment by magnarem** [comment]
Added /metrics prometheus endpoint for catalog rebuilder. https://catalog-rebuilder.s-enda-dev.k8s.met.no/metrics
Now the following is exposed:

```
# HELP archive_files Total number of mmd files in archive repository
# TYPE archive_files counter
archive_files 123390
# HELP csw_records Total number of records files in csw database
# TYPE csw_records counter
csw_records 123388
# HELP solr_docs Total number of documents in solr index
# TYPE solr_docs counter
solr_docs 123388
# HELP rejected_files Total number of mmd files rejected by dmci
# TYPE rejected_files counter
rejected_files 0
# HELP workdir_files Total number of mmd files in distributor cache
# TYPE workdir_files counter
workdir_files 0
# HELP parent_uuid_list Total number of parent identifiers in parent-uuid-list.xml
# TYPE parent_uuid_list counter
parent_uuid_list 18
# HELP csw_parent_count Total number of parents registered in csw
# TYPE csw_parent_count counter
csw_parent_count 15
# HELP csw_distinct_parent_ids Total number of distinct parent identifiers in csw
# TYPE csw_distinct_parent_ids counter
csw_distinct_parent_ids 15
# HELP solr_parent_count Total number of parents registered in solr
# TYPE solr_parent_count counter
solr_parent_count 15
# HELP solr_parent_unique Total number of unique parent identifiers in solr
# TYPE solr_parent_unique counter
solr_parent_unique 15
# HELP dmci_disk_usage_total Total disk space in bytes dmci-data
# TYPE dmci_disk_usage_total gauge
dmci_disk_usage_total 10464022528
# HELP dmci_disk_usage_used Used disk space in bytes dmci-data
# TYPE dmci_disk_usage_used gauge
dmci_disk_usage_used 2486337536
# HELP dmci_disk_usage_free Free disk space in bytes dmci-data
# TYPE dmci_disk_usage_free gauge
dmci_disk_usage_free 7960907776
```

So then we can make prometheus rules for alerts if the catalog differ or rejected files grows to much. Also monitoring the disk usage of the dmci PVC.

Consider this as closed.

**Comment by charlienegri** [comment]
great!! so which rules should I add for these metrics?
something about the rejected_files number being  > than a given threshold (which?), and then what do you mean by "if the catalog differ"?
the pvc usage is already monitored for all the pods via a rule for a standard k8s metrics

**Comment by charlienegri** [comment]
👍 thanks, will work on it

**Comment by charlienegri** [comment]
I see that the metrics are duplicated, like, each query gives a double result one with `cluster_node` and one without   
see for example https://prometheus-fou-b.met.no/fou-prom/graph?g0.expr=solr_docs%7Bjob%3D~%22s-enda-dev%2Fcatalog-rebuilder-flask%22%7D&g0.tab=1&g0.stacked=0&g0.show_exemplars=0&g0.range_input=1h
are they equivalent? is it ok if I pick only one of the two e.g. https://prometheus-fou-b.met.no/fou-prom/graph?g0.expr=solr_docs%7Bjob%3D~%22s-enda-dev%2Fcatalog-rebuilder-flask%22%2C%20cluster_node%3D~%22.%2B%22%7D&g0.tab=1&g0.stacked=0&g0.show_exemplars=0&g0.range_input=1h?

**Comment by magnarem** [comment]
I do not know why the metrics are duplicated, but to use one of the two, should be ok.
