### ISSUE TITLE
Implement Parent/Child relation integrity check

### ISSUE THREAD

**Issue by magnarem** [metno/catalog-rebuilder#6]
In the status page. It will be good to also show the integrity between the catalogs of the number of parents and if there are children with missing parents. This should be quite feasible to implement.

**Comment by magnarem** [comment]
started this. Possible working version. Need to update the html with more descriptive info

**Comment by magnarem** [comment]
This is now implemented and can be closed, if not more implementation is needed

**Comment by mortenwh** [comment]
was there a PR with this one? anyway, I'll close it now. Thanks!
